name: Build

on: 
  push: 
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: macOS-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,iOS=latest,name=iPhone 11']

    steps:
    - uses: actions/checkout@v2
    - name: Build
      continue-on-error: false
      run: |
            swift package init --type library
            swift package generate-xcodeproj
            swift build -v
      env: 
        destination: ${{ matrix.destination }}
    - name: Example Build
      env: 
        destination: ${{ matrix.destination }}
      run: |
        pod repo update
        pod install
        cd Example
        xcrun simctl create iPhone11 com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-3
        pod repo update
        pod install
        xcodebuild -scheme iOSExample -destination "${destination}" build
