name: Build

on: 
  push: 
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: macOS-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,iOS=13.3,name=iPhone11']

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        gem install cocoapods --pr
        pod repo update
    - name: Build  
      run: |
        pod deintegrate
        pod install
    - name: Start Example
      run: cd Example
    - name: Example Build
      env: 
        destination: ${{ matrix.destination }}      
      run: |
        xcrun simctl create iPhone11 com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-3
        pod deintegrate
        pod install
        xcodebuild -scheme iOSExample -allowProvisioningUpdates -destination "${destination}" -UseModernBuildSystem=NO build
